#!/usr/bin/env bash
#
# File Name:       yuv-mplayer.sh
# Created:         06-11-2017
# Last modified:   Mon 06 Nov 2017 03:49:52 PM CET
# Author:          Thomas Goldbrunner <thomas.goldbrunner@tum.de>
#
#
# Copyright (c) 2017 Thomas Goldbrunner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

__usage() {
  echo "Usage: yuv-mplayer <format> <filename>"
  echo "Available formats:"
  echo "  -720p : 1280x720"
  echo "  -1080p : 1920x1080"
}

if [ ! "$(which mplayer)" ] ; then
  echo "Error: mplayer executable not found."
  exit 1
fi

if [ "$#" != 2 ] ; then
  __usage
  exit 0
fi

case "$1" in
  "-720p")
    width="1280"
    height="720"
    ;;
  "-1080p")
    width="1920"
    height="1080"
    ;;
  *)
    __usage
    exit 0
    ;;
esac

mplayer -demuxer rawvideo -rawvideo w="$width":h="$height":format=i420 "$2"

